### ISSUE TITLE
Grit::Git#sh has problem with stdout.read on Passenger

### ISSUE THREAD

**Issue by robertsosinski** [mojombo/grit#10]
Trying to use Grit on Passenger, and any command that uses Grit::Git#sh will return empty.  One example is Grit::Repo#log, which will return an array of commits, except when using Passenger, which will return an empty array.

On Grit 2.0.0, I think the problem is on lib/grit/git.rb:250, where stdout.read(1024) always returns nil on Passenger, while other environments will return the Git output.

**Comment by zmalltalker** [comment]
I'm having the same issue here. Debugging and messing around, I found that although stdout has nothing, stderr does. In my case it read:

/usr/bin/env: git: No such file or directory. 

I was only able to reproduce this on Centos, and I suspect SELinux to be involved.
It's quite easy to get around, since Grit::Git's git_binary has an attr_accessor, but maybe stdout should be checked, since the error message is a lot more helpful than an empty string...

**Comment by kbrock** [comment]
Found this issue on a redmine thread as well.
Under passenger, the bin path is different from the regular user

**Comment by sfsekaran** [comment]
Yeah, found this issue because we were experiencing the same symptoms. I wish Grit would either throw an error or log something when it fails to find the git binary.

**Comment by bobbywilson0** [comment]
This looks to be related to #2

**Comment by sfsekaran** [comment]
Yeah, it totally looks like #2 is a generalization of this issue.

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
