### ISSUE TITLE
Files are deleted after commit

### ISSUE THREAD

**Issue by tonini** [mojombo/grit#132]
Hi,

After trying one of the examples all the files are deleted in the repository (marked as ready to be commited):

``` ruby
require 'grit'

count = 1
Dir.chdir("localstore") do
  r = Grit::Repo.new('.')
  i = r.index
  while(count < 10) do
    fname = Time.now.to_i.to_s + count.to_s
    i.add(fname, 'hello ' + fname)
    count += 1
  end
  count = 5
  while(count < 10) do
    puts "HELLO"
    fname = Time.now.to_i.to_s + count.to_s
    i.add('test/' + fname, 'hello ' + fname)
    count += 1
  end
  puts i.commit('my commit')
  puts i.inspect
end
```

Git Version => 1.7.4.2 (maybe that's the problem?)

**Comment by whitehat101** [comment]
This is a case of advanced git use and a poorly commented example.

No files are created in this test. However the git index is modified. The contents of the files are supplied as strings in `i.add(fname, 'hello ' + fname)`.  The index is committed, but since files weren't created in the first place they become 'deleted' because they are not in the repo.

If you run `git checkout master` in the repo after running the example, you will see what you expected.

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
