### ISSUE TITLE
Grit::Repo#commits_since incorrectly lists all commits

### ISSUE THREAD

**Issue by todd-a-jacobs** [mojombo/grit#133]
I have a repository with five total commits, and zero commits for today. From the command line:

```
$ git log --since='2012-07-12' --oneline | wc -l
0
```

However, with Grit v2.5.0, #commits_since incorrectly lists _all_ the commits in the repository:

```
> repo.class
=> Grit::Repo

> repo.commits_since('master', '2012-07-12').count
=> 5
```

**Comment by snh** [comment]
Unless I'm misreading the source code, I believe Grit expects a `Time` object for `since`.

Below are some examples that should return commits since 1st August 2012 (examples provided for either Local Time or UTC Time):

Using the `local` class method of `Time` to generate a `Time` object for 1st August 2012 Midnight **Local Time**:

``` ruby
commits = repo.commits_since('master', Time.local(2012, 8, 1)) 
```

Or using the `utc` class method of `Time` to generate a `Time` object for 1st August 2012 Midnight **UTC Time**:

``` ruby
commits = repo.commits_since('master', Time.utc(2012, 8, 1))
```

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
