### ISSUE TITLE
Needs Help

### ISSUE THREAD

**Issue by trans** [mojombo/grit#77]
Why is there no #checkout? Why is there so little documentation? And why is there 46 open issues!? ;-)

Seriously though, it seems like grit is the "go to" library for interfacing with Git using Ruby, but I am having a rough time figuring out how do a lot of the most basic things.

Since grit is a the heart of GitHub it would really helpful if you could put a guy on beefing up this library and it's docs.

**Comment by banister** [comment]
@trans, I found Grit a bit of a pain at first (due to lack of docs), but it's actually pretty straight forward once you browse the source. Have a look [at this tool](https://github.com/pry/pry/wiki/Source-browsing), which makes learning a lib that doesn't have docs a lot easier.

Also, and i dont mean to be a smartass, but i'm sure they'd appreciate pull requests with documentation ;)

**Comment by trans** [comment]
@branster thanks for the link I'll see if it can help. I'm trying to figure out how to copy a directory into gh-pages branch and pushing ti via grit.

I would love to make some pull requests with docs if I understood things enough to write them --which is actually why I actually need them ;-)

**Comment by bobbywilson0** [comment]
@trans It is easier for us to help if you are telling us what you are trying to accomplish. Complaining about the library in 'Issues' isn't a very good way to get support. I would do your best to read through the documentation and tests, then create an Issue when you are trying to solve a specific problem. Please consider closing this issue as you are adding noise with this.

**Comment by trans** [comment]
I'm trying to figure out how to use the library. One thing that stumped me was how to checkout a branch --which seems pretty basic. But hey, what can I tell you, if you don't want to here it?
